INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Ford Ka 1.0 SE Trail (Flex) 2018', 52900.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/ka.webp', 'Flex, Final da placa 3, distribuição eletrônica de frenagem, airbag motorista, freios ABS, airbag passageiro, ar-condicionado, direção elétrica', '2017 / 2018', 59056, 'Prata', 'Manual');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Hyundai Tucson GLS 1.6 GDI Turbo (Aut) 2019', 140000.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/tucson.webp', 'Gasolina, Final da placa 5, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral, distribuição eletrônica de frenagem', '2018 / 2019', 41111, 'Branca', 'Automática');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Volkswagen Amarok 3.0 V6 CD Highline 4x4 2019', 215000.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/amarok.webp', 'Diesel, Final da placa 0, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral, distribuição eletrônica de frenagem', '2018 / 2019', 90543, 'Preta', 'Automática');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Jeep Renegade Sport 1.8 (Aut) (Flex) 2018', 89900.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/renegade.webp', 'Flex, Final da placa 2, distribuição eletrônica de frenagem, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral', '2018 / 2018', 62900, 'Cinza', 'Automática');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Toyota Corolla 2.0 XEi Dynamic Force 2021', 139900.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/corolla.webp', 'Flex, Final da placa 4, distribuição eletrônica de frenagem, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral, controle de tração', '2020 / 2021', 376, 'Preta', 'Automática');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Ford Ranger (Cabine Dupla) Ranger 2.2 TD XLS CD 4x4 2018', 147900.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/ranger.webp', 'Diesel, Final da placa 9, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral, distribuição eletrônica de frenagem', '2017 / 2018', 104064, 'Prata', 'Manual');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Honda Civic 1.5 Turbo Touring CVT 2020', 155000.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/civic.webp', 'Gasolina, Final da placa 3, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral, distribuição eletrônica de frenagem', '2019 / 2020', 39794, 'Branca', 'Automática');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Fiat Toro 2.0 TDI Volcano 4WD (Aut) 2021', 164900.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/toro.webp', 'Diesel, Final da placa 8, airbag motorista, alarme, freios ABS, airbag passageiro, distribuição eletrônica de frenagem', '2020 / 2021', 37305, 'Branca', 'Automática');
INSERT INTO tb_product (name, price, image_Uri, description, year, kilometers, color, transmission) VALUES ('Land Rover Range Rover Sport 3.0 SDV6 HSE 4wd 2015', 309000.00, 'https://raw.githubusercontent.com/renatoabreu14/backend-locar/main/images/rangerover.webp', 'Diesel, Final da placa 0, distribuição eletrônica de frenagem, airbag motorista, alarme, freios ABS, airbag passageiro, airbag lateral, controle de tração', '2015 / 2015', 56840, 'Cinza', 'Automática');
